{
  "hash": "d174b181bcd63880de8774ed13c41644",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"DATA 202 - Week 8\"\nsubtitle: \"Exploratory Data Analysis\"\nauthor: \"Nathan Alexander, PhD\"\ninstitute: \"Center for Applied Data Science and Analytics\"\nformat: \n  html: default\n  revealjs:\n    output-file: week08-slides.html\n    height: 900\n    width: 1600\n    smaller: false\n    scrollable: true\n    slide-number: c/t #< collapsted/total\n    logo: \"img/howard-logo.jpg\"\n    footer: \"[Course Data GitHub](https://github.com/data-202)\"\n    toc: false\n    echo: true\n    incremental: false\n---\n\n\n\n\n\n\n## Part I: Context\n\nThis week we will outline exploratory data analysis through a set of case studies. Each case study provides one example of the various decision making processes needed in a critical quantitative research framework. The included cases focus on more heavily on theories and frameworks and the related practices around modeling and statistical inference.\n\n------------------------------------------------------------------------\n\n### Case Study: The Murder of George Floyd\n\nWhat do you know about a man named George Floyd and the events that occurred on May 25, 2020?\n\n![[Image from Time.com](https://time.com/5957292/time-cover-ange-hillz-george-floyd-portrait/){target=\"_blank\"}](https://api.time.com/wp-content/uploads/2021/04/TIM210510_Floyd.CoverB.jpg?quality=85&w=2400){width=\"75%\"}\n\n------------------------------------------------------------------------\n\nGeorge Floyd was murdered by a police officer in broad daylight. His murder resulted in a series of protests and expanded the already longstanding discussions around racism, state violence, and police brutality in the United States. Consider [How George Floyd Was Killed in Police Custody](https://www.nytimes.com/2020/05/31/us/george-floyd-investigation.html){target=\"_blank\"} to get a step-by-step reconstruction of the murder.\n\n#### Yahoo! News Race and Justice poll results\n\nThe Yahoo! News Race and Justice poll was conducted in 2020 after the killing of George Floyd. There is pre-loaded data set located in R. A complete description of the data is as follows:\n\n> Results from a Yahoo! News poll conducted by YouGov on May 29-31, 2020. In total 1060 U.S. adults were asked a series of questions regarding race and justice in the wake of the killing of George Floyd by a police officer. Results in this data set are percentages for the question, \"Do you think Blacks and Whites receive equal treatment from the police?\" For this particular question there were 1059 respondents.\n\nFor efficient access, poll results are stored in a replica of the `yahoo_data` data frame located in the `critstats` package.\n\n------------------------------------------------------------------------\n\n#### Exploratory Data Analysis\n\nThe process of exploratory data analysis will vary across projects. It is helpful if your exploratory analysis is directed by a set of clear questions and introductory tasks. The exploring data phase should not be solely used for cleaning data, although the two steps are often intertwined.\n\nWe will structure our exploratory analysis around three steps:\n\n-   *Information*: Gaining a solid understanding of each variable and its observations\n\n-   *Shape*: Gaining a better feel for the \"shape\" and distribution of the observations\n\n-   *Measures*: Checking base assumptions for any forthcoming analysis\n\nThese steps can help guide more concrete theory building and modeling.\n\n------------------------------------------------------------------------\n\n#### Step 0: Load the `critstats` and other useful libraries\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(critstats)\nlibrary(tidyverse)\nlibrary(ggplot2)\nlibrary(dplyr)\n```\n:::\n\n\n\n\n\n\n------------------------------------------------------------------------\n\n#### Step 1: Access data\n\nLoad the `yahoo_data` data frame and use the `str()` command.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nyahoo <- critstats::yahoo_data\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(yahoo)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   race_eth           response        \n Length:1059        Length:1059       \n Class :character   Class :character  \n Mode  :character   Mode  :character  \n```\n\n\n:::\n\n```{.r .cell-code}\nglimpse(yahoo)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1,059\nColumns: 2\n$ race_eth <chr> \"White\", \"White\", \"White\", \"White\", \"White\", \"White\", \"White\"…\n$ response <chr> \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"Yes\"…\n```\n\n\n:::\n:::\n\n\n\n\n\n\n------------------------------------------------------------------------\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(yahoo)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 2\n  race_eth response\n  <chr>    <chr>   \n1 White    Yes     \n2 White    Yes     \n3 White    Yes     \n4 White    Yes     \n5 White    Yes     \n6 White    Yes     \n```\n\n\n:::\n\n```{.r .cell-code}\ntail(yahoo)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 2\n  race_eth response\n  <chr>    <chr>   \n1 Other    Not sure\n2 Other    Not sure\n3 Other    Not sure\n4 Other    Not sure\n5 Other    Not sure\n6 Other    Not sure\n```\n\n\n:::\n:::\n\n\n\n\n\n\n------------------------------------------------------------------------\n\n#### Step 2: Outline a series of questions and/or small tasks\n\nAs an early start, we can use the output above to start our exploration.\n\nTo help focus these explorations, it is helpful to outline a set of questions or tasks. These tasks and questions can help identify some of the key goals of the exploratory data analysis. Wickham, Çetinkaya-Rundel, & Grolemund (2023) talk about this at length in the [Exploratory Data Analysis section](https://r4ds.hadley.nz/eda) of the [*R for Data Science*](https://r4ds.hadley.nz/) text.\n\nFor this exploration, our goal is to understand the proportion of observations in each variable.\n\nTo accomplish this goal, we can outline two questions around three tasks.\n\n| Questions                                       | Tasks & Detail                                     |\n|:----------------------------------|:------------------------------------|\n| Question 1: How are observations distributed?   | Task 1.1: Create a table of variable counts        |\n|                                                 | Task 1.2: Create a table of variable proportions   |\n| Question 2: How can we visualize distributions? | Task 2.1: Create two to three basic visualizations |\n\n------------------------------------------------------------------------\n\n#### Step 3: Flow through each tasks\n\nTask 1.1: Create a table of variable counts\n\nTask 1.2: Create a table of variable proportions\n\nTask 2.1: Create two to three basic visualizations\n\n------------------------------------------------------------------------\n\n### Information\n\nGain a solid understanding of each variable and its observations.\n\n------------------------------------------------------------------------\n\n#### Task 1.1: Create a table of variable counts\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(yahoo$race_eth)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n   Black Hispanic    Other    White \n     101      104       82      772 \n```\n\n\n:::\n\n```{.r .cell-code}\ntable(yahoo$response)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n      No Not sure      Yes \n     700      123      236 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n------------------------------------------------------------------------\n\n##### Task 1.2: Create a table of variable proportions\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.table(table(yahoo$race_eth))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     Black   Hispanic      Other      White \n0.09537299 0.09820585 0.07743154 0.72898961 \n```\n\n\n:::\n\n```{.r .cell-code}\nprop.table(table(yahoo$response))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n       No  Not sure       Yes \n0.6610009 0.1161473 0.2228517 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n------------------------------------------------------------------------\n\n##### Counts and proportions\n\nThe previous output provides more information than may be immediately noted:\n\n-   Lists the various labels for each variable\n\n-   Presents the distribution of observations across each label\n\n-   Specific relations can be pointed to the study framing\n\n-   Early insight into base assumptions\n\n------------------------------------------------------------------------\n\n### Shape\n\nGain a better feel for the \"shape\" and distribution of the observations.\n\n------------------------------------------------------------------------\n\n##### Task 2.1: Create three to four basic visualizations\n\nWe introduce some basic features of \\``ggplot()` here to complete the task.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# start with the plot outline\nggplot(yahoo)\n```\n\n::: {.cell-output-display}\n![](week08_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\n------------------------------------------------------------------------\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# add the variable categories to the plot using aes()\nggplot(yahoo, aes(x = race_eth))\n```\n\n::: {.cell-output-display}\n![](week08_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\n------------------------------------------------------------------------\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# add the bars to the plot using + geom_bar()\nggplot(yahoo, aes(x = race_eth)) +\n  geom_bar()\n```\n\n::: {.cell-output-display}\n![](week08_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\n------------------------------------------------------------------------\n\n::: {.callout-tip icon=\"false\"}\n## **EXERCISE**\n\nCreate a bar plot for the `response` variable.\n\nWhat other plots could you create?\n:::\n\nWickham, Çetinkaya-Rundel, & Grolemund (2023) have a detailed section on [data visualization](https://r4ds.hadley.nz/data-visualize) in the [*R for Data Science*](https://r4ds.hadley.nz/) text.\n\n------------------------------------------------------------------------\n\n### Measures\n\nCheck base assumptions for any forthcoming analysis.\n\nTo complete this step, we delve into some of the assumptions and foundations surrounding the use of sample data versus population data. The mathematical foundations allow us to understand how to compute measures and differences. The assumptions provide direction for any further modeling practices.\n\nWe explore this more in part II.\n\n------------------------------------------------------------------------\n\n## Part II: Content\n\n------------------------------------------------------------------------\n\n### A guiding example\n\nLet us begin with a summary of responses to a survey sparked by the killing of George Floyd.\n\n| Response | Total |\n|:--------:|:-----:|\n|    No    |  700  |\n|   Yes    |  236  |\n\n: Summary of survey response data[^1] {.striped .hover}\n\n[^1]: Respondents who selected **'Not sure'** on the survey were moved from this analysis.\n\nThe study sample $n = 936$. Please take note of the table's footnote.\n\nAs of now, we know very little about the survey (i.e., the context has been stripped away).\n\n#### An initial question\n\nIs there a difference in the survey responses?\n\n------------------------------------------------------------------------\n\n#### Framing proportions\n\nAs you learn about hypothesis testing, you want to understand the nature of variable associations. There are many approaches to how we measure associations. One we'll explore extensively is differences in proportions of two dichotomous variables.\n\nFirst, we add a third column to our table by computing the proportion in each row:\n\n$$ P(No) = \\frac{\\text{Number of respondents who replied No}}{n} $$\n\n$$ P(Yes) = \\frac{\\text{Number of respondents who replied Yes}}{n} $$\n\n------------------------------------------------------------------------\n\n#### Understanding proportions\n\n| Response | Total | Proportion |\n|:--------:|:-----:|:----------:|\n|    No    |  700  |  $0.7478$  |\n|   Yes    |  236  |  $0.2522$  |\n\n: Summary of survey response data with proportion column {.striped .hover}\n\nSo we have $P(No) = 0.7478$ and $P(Yes) = 0.2522$.\n\nThis is a sample. Be mindful of the notes about sampling and sampling error.\n\n**What can these proportions tell us about the data?**\n\n------------------------------------------------------------------------\n\n### A closer look\n\nLet's look at a preview panel of the full data set.\n\n|   ID   | Race     | Response |\n|:------:|----------|----------|\n|   1    | White    | Yes      |\n|   2    | White    | Yes      |\n|   .    | .        | .        |\n|  773   | Black    | Yes      |\n|  774   | Black    | Yes      |\n|   ..   | ..       | ..       |\n|  874   | Hispanic | Yes      |\n|  875   | Hispanic | Yes      |\n|  ...   | ...      | ...      |\n| $1059$ | Other    | Not sure |\n\n: Preview of full survey response data set {.striped .hover}\n\n------------------------------------------------------------------------\n\nWhen we format the data into tables, there are multiple categories to consider.\n\nIn the table below, the `race` variable is listed in rows.\n\n| Race     | No                 | Yes                 |\n|----------|--------------------|---------------------|\n| Black    | Black $\\cap$ No    | Black $\\cap$ Yes    |\n| Hispanic | Hispanic $\\cap$ No | Hispanic $\\cap$ Yes |\n| Other    | Other $\\cap$ No    | Other $\\cap$ Yes    |\n| White    | White $\\cap$ No    | White $\\cap$ Yes    |\n\n: Race in rows {#tbl-first}\n\nRecall that the $\\cap$ represents \"and\" while the $\\cup$ represents \"or\" in logic.\n\n------------------------------------------------------------------------\n\nIn the table below, the `response` variable is listed in rows.\n\n| Response | Black            | Hispanic            | Other            | White            |\n|---------------|---------------|---------------|---------------|---------------|\n| No       | No $\\cap$ Black  | No $\\cap$ Hispanic  | No $\\cap$ Other  | No $\\cap$ White  |\n| Yes      | Yes $\\cap$ Black | Yes $\\cap$ Hispanic | Yes $\\cap$ Other | Yes $\\cap$ White |\n\n: Response in rows {#tbl-second}\n\n------------------------------------------------------------------------\n\nWe use our understanding of probability to generate a reconstruction for the response 'No'.\n\n$$ P(No) = \\dfrac{\\text{No} \\cap \\text{Black}}{n} + \\dfrac{\\text{No} \\cap \\text{Hispanic}}{n} + \\dfrac{\\text{No} \\cap \\text{Other}}{n} + \\dfrac{\\text{No} \\cap \\text{White}}{n} $$\n\nWe generate a parallel construction for the response 'Yes'.\n\n$$ P(Yes) = \\dfrac{\\text{Yes} \\cap \\text{Black}}{n} + \\dfrac{\\text{Yes} \\cap \\text{Hispanic}}{n} + \\dfrac{\\text{Yes} \\cap \\text{Other}}{n} + \\dfrac{\\text{Yes} \\cap \\text{White}}{n} $$\n\n#### Summary values\n\nAdding values to the table will give us a more complete picture of the data.\n\n| Response | Black | Hispanic | Other | White |\n|:--------:|:-----:|:--------:|:-----:|:-----:|\n|    No    |  92   |    75    |  47   |  486  |\n|   Yes    |   6   |    15    |  14   |  201  |\n\n: Responses to a survey question by race {.striped .hover}\n\n------------------------------------------------------------------------\n\nUse the table to calculate `Response` probabilities:\n\n| Response | Black | Hispanic | Other | White | Total |\n|:--------:|:-----:|:--------:|:-----:|:-----:|------:|\n|    No    |  92   |    75    |  47   |  486  |   700 |\n|   Yes    |   6   |    15    |  14   |  201  |   236 |\n\n: Responses to a survey question by race {.striped .hover}\n\nGather response probabilities for `No` by dividing each cell by the sample size.\n\n$$ P(No) = \\dfrac{92}{936} + \\dfrac{75}{936} + \\dfrac{47}{936} + \\dfrac{486}{936} = \\dfrac{700}{936} = 0.7478 $$ Gather response probabilities for `Yes` by dividing each cell by the sample size.\n\n$$ P(Yes) = \\dfrac{6}{936} + \\dfrac{15}{936} + \\dfrac{14}{936} + \\dfrac{201}{936} = \\dfrac{236}{936} = 0.2522 $$ We will use this framing to compute proportions for each cell but in R.\n\n------------------------------------------------------------------------\n\nGiven that we want to explore the data in more detail and understand any base associations, we need to revisit our framing and consider some additional tasks.\n\n### Returning to the framework\n\nA basic analysis goes a long way in determining our next steps.\n\nWith this base analytic exercises, you may want to ask: *What is the research question?*\n\nWhat are the **main** or **primary** theoretical constructions?\n\n-   First, examine the literature and annotate specific citations.\n\n-   Next, construct a framework for the various interpretations.\n\n    -   What are the similarities across theoretical constructions?\n\n    -   What are the main differences across theoretical constructions?\n\n    -   How does a nuanced view of the history of the issue improve our understanding?\n\nBased on your background analyses, what is the hypothesis?\n\n------------------------------------------------------------------------\n\n## Part III: Code\n\n------------------------------------------------------------------------\n\n#### Setting things up\n\nAs a general rule, always load the appropriate libraries at the start of your analyses.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load our libraries\nlibrary(critstats)\nlibrary(tidyverse)\nlibrary(descr)\nlibrary(Hmisc)\n```\n:::\n\n\n\n\n\n\nIn this case:\n\n-   `critstats` contains the `yahoo_data` that we'd like to analyze.\n\n-   `tidyverse` contains the set of functions to help us work with our data\n\n-   `descr` and `Hmisc` contain useful functions to analyze social science data.\n\nIf you receive an error, you may need to use the `install.packages()` commands first.\n\n------------------------------------------------------------------------\n\n#### Load the data\n\nInspect the data documentation and contents of the data.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# access the yahoo_data\n??yahoo_data\nyahoo_data # \"Do you think Blacks and Whites receive equal treatment from the police?\"\n```\n:::\n\n\n\n\n\n\nWhile the specific wording of the question may not fit our theoretical framing (e.g. `Blacks` and `Whites`), it is useful to consider what information and insights can be gathered from the data.\n\nHere, theory and the literature become important components to outlining your analytic plan.\n\n------------------------------------------------------------------------\n\n#### Clean your data\n\nThe data in the `yahoo_data` set is already cleaned and prepped. However, when you conduct your own analyses, you will need to follow the series of steps outlined in previous assignments.\n\nAs example, [Lab 1](labs/lab1.html) is a great resource on cleaning.\n\n------------------------------------------------------------------------\n\n#### Explore your data\n\nGiven that we are analyzing categorical data, we will continue from earlier when we created a series of tables. These tables will allow us to gather a sense of the data.\n\nOur first table will be of the variable `race_eth`.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create a table of the race_eth\ntable(yahoo_data$race_eth)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n   Black Hispanic    Other    White \n     101      104       82      772 \n```\n\n\n:::\n:::\n\n\n\n\n\n\nWhat do you notice? What do you wonder?\n\n------------------------------------------------------------------------\n\n#### Explore your data\n\nOur second table will be of the variable `response`.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create a table of the race_eth\ntable(yahoo_data$response)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n      No Not sure      Yes \n     700      123      236 \n```\n\n\n:::\n:::\n\n\n\n\n\n\nWhat do you notice? What do you wonder?\n\n------------------------------------------------------------------------\n\n#### Modify your data\n\nMake the necessary modifications to your data.\n\nHere I set the `yahoo_data` to `df` and rename the `race_eth` variable.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- yahoo_data # set the yahoo_data to df\ndf <- df %>% \n  rename(\"race\" = \"race_eth\") # rename the race_eth variable to race\n```\n:::\n\n\n\n\n\n\n------------------------------------------------------------------------\n\n#### Get the sample size\n\nWhen looking at the table, it may be useful to get a sense of the *proportions*.\n\nWe'll begin with getting the sample size.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# get a quick count of the sample size\ncount(df) # the count function can collect the sample size, n, of a tibble\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n      n\n  <int>\n1  1059\n```\n\n\n:::\n:::\n\n\n\n\n\n\nThe tables give us the **frequency** of each category.\n\nThe sample size will help us get the **relative frequency** of each category.\n\n------------------------------------------------------------------------\n\n#### Relative frequencies by race\n\nGet the relative frequencies for the `race` variable.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf %>% \n  count(race) %>% \n  mutate(prop = prop.table(n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 3\n  race         n   prop\n  <chr>    <int>  <dbl>\n1 Black      101 0.0954\n2 Hispanic   104 0.0982\n3 Other       82 0.0774\n4 White      772 0.729 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n------------------------------------------------------------------------\n\n#### Relative frequencies by response\n\nGet the relative frequencies for the `response` variable.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf %>% \n  count(response) %>% \n  mutate(prop = prop.table(n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  response     n  prop\n  <chr>    <int> <dbl>\n1 No         700 0.661\n2 Not sure   123 0.116\n3 Yes        236 0.223\n```\n\n\n:::\n:::\n\n\n\n\n\n\n------------------------------------------------------------------------\n\n#### Generate a `crosstab` of `race` and `response`\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrosstab(df$response, df$race, plot=F)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Cell Contents \n|-------------------------|\n|                   Count | \n|-------------------------|\n\n=======================================================\n               df$race\ndf$response    Black   Hispanic   Other   White   Total\n-------------------------------------------------------\nNo                92         75      47     486     700\n-------------------------------------------------------\nNot sure           3         14      21      85     123\n-------------------------------------------------------\nYes                6         15      14     201     236\n-------------------------------------------------------\nTotal            101        104      82     772    1059\n=======================================================\n```\n\n\n:::\n:::\n\n\n\n\n\n\nSet `plot=T` if you want to see a visual plot of the data. What do you notice? What do you wonder?\n\n------------------------------------------------------------------------\n\n#### Standardize the frequencies\n\nRaw frequencies can be hard to read in a crosstab, especially since column totals are not equal.\n\nAdd `prop.c = T` to get column percentages\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrosstab(df$response, df$race, plot=F, prop.c=T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Cell Contents \n|-------------------------|\n|                   Count | \n|          Column Percent | \n|-------------------------|\n\n=======================================================\n               df$race\ndf$response    Black   Hispanic   Other   White   Total\n-------------------------------------------------------\nNo               92         75      47     486     700 \n               91.1%      72.1%   57.3%   63.0%        \n-------------------------------------------------------\nNot sure          3         14      21      85     123 \n                3.0%      13.5%   25.6%   11.0%        \n-------------------------------------------------------\nYes               6         15      14     201     236 \n                5.9%      14.4%   17.1%   26.0%        \n-------------------------------------------------------\nTotal           101        104      82     772    1059 \n                9.5%       9.8%    7.7%   72.9%        \n=======================================================\n```\n\n\n:::\n:::\n\n\n\n\n\n\nWe also refer to crosstabs as *contingency tables*; the percentages provide *conditional probabilities*. What do you notice? What do you wonder?\n\n------------------------------------------------------------------------\n\n### Hypothesis testing with crosstab\n\nDevelop (or refine) your research question(s).\n\nExamining the relationship between two variables.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# research inquiry: is there a relationship between the race and response variables?\n# data: survey results from the Yahoo! News race and justice poll\n# note(s): response contains three levels: Yes, No, and Not sure\n```\n:::\n\n\n\n\n\n\nAdd your research inquiry/question to your preamble.\n\nNotes help you remember import information for writing code. You can also put them in-line.\n\n------------------------------------------------------------------------\n\n### Null and alternative hypothesis for a $\\chi^2$ test are:\n\n-   $H_0$: No relationship. The two variables are statistically independent.\n\n-   $H_1$: There is a relationship. The two variables are not statistically independent.\n\nNotice that $H_1$ does not give us information about the direction or strength of the relationships. To test the null hypothesis, we will calculate the $\\chi^2$ statistic:\n\n$$\\chi^2 = \\sum \\dfrac{(O-E)^2}{E}$$\n\nWhere\n\n-   $O$ is the observed frequency for each cell\n\n-   $E$ is the expected frequency for each cell\n\n    -   The expected frequency is what we'd expected if there is no relationship ($H_0$ is true)\n\n------------------------------------------------------------------------\n\n#### Create a crosstab with raw frequencies\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrosstab(df$response, df$race, plot=F)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Cell Contents \n|-------------------------|\n|                   Count | \n|-------------------------|\n\n=======================================================\n               df$race\ndf$response    Black   Hispanic   Other   White   Total\n-------------------------------------------------------\nNo                92         75      47     486     700\n-------------------------------------------------------\nNot sure           3         14      21      85     123\n-------------------------------------------------------\nYes                6         15      14     201     236\n-------------------------------------------------------\nTotal            101        104      82     772    1059\n=======================================================\n```\n\n\n:::\n:::\n\n\n\n\n\n\n------------------------------------------------------------------------\n\n#### Sampling error\n\n*An important note about sampling error*\n\nThere appears to be a relationship between the variable `response` and `race`.\n\nHowever, the data are from a sample. We do not and should not infer that there is a relationship at the population level, but only for the sample data we are analyzing.\n\nEarlier, we saw the difference in proportions by the column differences for \"Yes\" and \"No\". Since we found that the overall population said \"No\" to the question of fair treatment, we want to take this into consideration when analyzing our data.\n\n------------------------------------------------------------------------\n\n#### Gather the expected frequencies\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrosstab(df$response, df$race,\n         expected=T, #Add expected frequency to each cell\n         plot=F)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Cell Contents \n|-------------------------|\n|                   Count | \n|         Expected Values | \n|-------------------------|\n\n=======================================================\n               df$race\ndf$response    Black   Hispanic   Other   White   Total\n-------------------------------------------------------\nNo                92         75      47     486     700\n                66.8       68.7    54.2   510.3        \n-------------------------------------------------------\nNot sure           3         14      21      85     123\n                11.7       12.1     9.5    89.7        \n-------------------------------------------------------\nYes                6         15      14     201     236\n                22.5       23.2    18.3   172.0        \n-------------------------------------------------------\nTotal            101        104      82     772    1059\n=======================================================\n```\n\n\n:::\n:::\n\n\n\n\n\n\n------------------------------------------------------------------------\n\n#### Add the chi-square contributions\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrosstab(df$response, df$race,\n         expected=T, #Add expected frequency to each cell\n         prop.chisq = T, #Total contribution of each cell \n         plot=F)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Cell Contents \n|-------------------------|\n|                   Count | \n|         Expected Values | \n| Chi-square contribution | \n|-------------------------|\n\n=========================================================\n               df$race\ndf$response     Black   Hispanic    Other   White   Total\n---------------------------------------------------------\nNo                 92         75       47     486     700\n                 66.8       68.7     54.2   510.3        \n                9.542      0.569    0.957   1.156        \n---------------------------------------------------------\nNot sure            3         14       21      85     123\n                 11.7       12.1      9.5    89.7        \n                6.498      0.305   13.828   0.243        \n---------------------------------------------------------\nYes                 6         15       14     201     236\n                 22.5       23.2     18.3   172.0        \n               12.107      2.885    1.000   4.874        \n---------------------------------------------------------\nTotal             101        104       82     772    1059\n=========================================================\n```\n\n\n:::\n:::\n\n\n\n\n\n\n------------------------------------------------------------------------\n\n#### Calculate degrees of freedom\n\nWe have $$df_{\\chi^2} = (r-1)(c-1)$$\n\nwhere r = number of rows in the table and c = number of columns in the table\n\n------------------------------------------------------------------------\n\nChi-square critical values\n\n![Chi-square critical values](img/wk8-b-1.png)\n\n------------------------------------------------------------------------\n\n#### Gather critical value of chi-square\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqchisq(.05, 6, lower.tail=F)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 12.59159\n```\n\n\n:::\n:::\n\n\n\n\n\n\n------------------------------------------------------------------------\n\n#### Get the chi-square statistic from R\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## get chi-square statistic\nchisq.test(df$response, df$race)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  df$response and df$race\nX-squared = 53.964, df = 6, p-value = 7.5e-10\n```\n\n\n:::\n:::\n\n\n\n\n\n\n------------------------------------------------------------------------\n\nOur focus should be on interpreting the output values.\n\nIn the output, you want to examine the following:\n\n-   Confirm $\\chi^2$ value and degrees of freedom.\n\n-   Notice more precise information about the p-value\n\n    -   Use this value to make sense of your research inquiry\n\n-   Does this p-value make sense *statistically* and *substantively*?\n\n------------------------------------------------------------------------\n\n#### describe some initial limitations of analysis\n\nAlways close out your analyses with a write up of limitations.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n### limitation 1: sampling error\n\n### limitation 2: category reductions\n\n### limitation 3: cases dropped\n\n### limitation 4: chi-square test\n```\n:::\n\n\n\n\n\n\n------------------------------------------------------------------------\n\n### **Next up**: Week 8\n",
    "supporting": [
      "week08_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}