---
title: "Annotated Bibliography"
format: 
  html: default
---

This page will support you with annotated bibliography assignment. In class, we will review how to develop a single file in Markdown format (.Rmd) to produce your annotated bibliography and course papers.

### Purpose

Every research paper should include a relevant literature review. 

Literature reviews can help your readers understand the need for your study, outline a paper's central thesis, and support readers in making sense of closely related results and findings. As a result, literature reviews can come in many different lengths and formats.

Doing a literature review is similar to doing any kind of research. A literature review should identify a central question, methodology, and also report findings. One effective way to start a literature review is to create an annotated bibliography.

Prior to starting an annotated bibliography, it is useful to develop a question that will help you explore and better understand theoretical and methodological connections.

### Framing a question

Literature reviews, like most research projects, can begin from a basic question.

-   Does income relate to the availability of resources for \[a population\]?

-   Are years of experience for \[a sample\] related to their perceptions of power?

Once you have identified a suitable question, you can use keywords to find sources for an annotated bibliography. The library website can be used to search periodicals or sources like the ERIC system, and you can also utilize popular search engines that house similar works, such as Research Rabbit and Google Scholar.

### Annotated bibliographies

An annotated bibliography is a list of sources about a specific research question or topic. Each source contains a short statement about the contents of the source (e.g., research paper, online article, or other scholarly and/or published works). Annotated bibliographies are not abstracts, although their length and structure may be similar.

Each source included in an annotated bibliography should begin with an appropriate citation of the source (in APA, MLA, or Chicago style) and a brief description of the purpose and contents of the source, as well as an evaluation or reflection. The inclusion of an evaluation or reflection when summarizing a published source is one effective way to tell the difference between the abstract and the annotation.

[View samples of annotated bibliographies](https://owl.purdue.edu/owl/general_writing/common_writing_assignments/annotated_bibliographies/annotated_bibliography_samples.html).
