---
title: "Case Study 1: Tuskegee Study of Untreated Syphillis in the Negro Male"
subtitle: "DATA 202 - Alexander"
format: 
  html: default
  pptx:
    toc: false
    reference_docx: "word-styles-reference.docx"
    fig_caption: true
  revealjs:
    output-file: week01-slides.html
    height: 900
    width: 1600
    smaller: false
    slide-number: c/t #< collapsted/total
    logo: "img/howard-logo.jpg"
    footer: "[Course Data GitHub](https://github.com/data-202)"
    toc: false
    echo: true
    incremental: false
geometry: margin=1.0in
editor_options:
  markdown:
    wrap: sentence
---

In Case Study 1, we will explore the ethics and quantification.

## Learning Objectives

The goal of this lab is to introduce you to or remind you of the historical case that contributed to the development of the Institutional Review Board. This case is the Tuskegee Study of Untreated Syphilis in the Negro Male. Case files can be found below and in [week 1](weeks/week01.qmd).

------------------------------------------------------------------------

## Learning Activities

By the end of this case study you will be able to:

1.  Identify historical issues of ethics and quantification
2.  Discuss the Institutional Review Board (IRB) and its purposes

## Case Study 1: Tuskegee Experiement of Untreated Syphillis

To help you prepare for our forthcoming discussions and readings, you should explore information about our first case study. One place to start is here: "The Tuskegee Experiment: Crash Course Black American History #29" in the video below:

<center>

<iframe width="560" height="315" src="https://www.youtube.com/embed/56gqCXlUCoE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen>

</iframe>

</center>
